OBJ_BALEFUL=asm_baleful.o

TARGET_BALEFUL=asm_baleful.${EXT_SO}
ALL_TARGETS+=${TARGET_BALEFUL}
STATIC_OBJ+=${OBJ_BALEFUL}

${TARGET_BALEFUL}: ${OBJ_BALEFUL}
	${CC} ${LDFLAGS} ${CFLAGS} -o ${TARGET_BALEFUL} ${OBJ_BALEFUL}